#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# github-setup.sh — put a freshly instantiated game on GitHub, ready for an agent team.
#
# Runs on the HOST (needs the host's gh auth). Idempotent — safe to re-run.
#   1. Create the GitHub repo if it does not exist; git init / commit / push `main`.
#   2. Labels, milestones (M0 Setup, M1 Design), Project + Status stages + views,
#      seeded groundwork epics/tickets as sub-issues  (scripts/github/setup_project.py).
#   3. Ruleset on the default branch: PR required, review threads resolved, no force
#      push. Required status checks are NOT added here (see WORKFLOW.md §5).
#   4. scripts/project-sync.sh to put every issue on the board.
#
# Usage:  ./scripts/github-setup.sh [--repo owner/name] [--private] [--title "Display Title"]
#   --repo     default: <gh user>/<folder name>
#   --private  create a private repo (default public)
#   --title    project board + issue placeholder title (default from package.json name, Title Case)
# Needs: gh with `repo` + `project` scopes:  gh auth refresh -h github.com -s project,read:project
# ---------------------------------------------------------------------------

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REPO=""
VISIBILITY="--public"
TITLE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --private) VISIBILITY="--private"; shift ;;
    --title) TITLE="$2"; shift 2 ;;
    -h | --help) sed -n '5,22p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

gh auth status >/dev/null 2>&1 || { echo "error: gh is not authenticated." >&2; exit 1; }
if ! gh auth status 2>&1 | grep -q "'project'"; then
  echo "error: gh token lacks the 'project' scope. Run:  gh auth refresh -h github.com -s project,read:project" >&2
  exit 1
fi

GH_USER="$(gh api user --jq .login)"
NAME="$(basename "$ROOT")"
[[ -n "$REPO" ]] || REPO="$GH_USER/$NAME"
SLUG="$(sed -n 's/^SLUG=//p' PORTS.env 2>/dev/null || true)"
[[ -n "$SLUG" ]] || SLUG="$NAME"
[[ -n "$TITLE" ]] || TITLE="$(echo "$NAME" | sed -E 's/[-_]+/ /g; s/\b(.)/\u\1/g')"

# ---- 1. repo + first push --------------------------------------------------
if ! gh repo view "$REPO" >/dev/null 2>&1; then
  echo "==> Creating GitHub repo $REPO"
  gh repo create "$REPO" "$VISIBILITY" --description "$TITLE — multiplayer game built from base-multiplayer-game" >/dev/null
fi
if [[ ! -d .git ]]; then
  git init -q -b main
fi
if ! git remote get-url origin >/dev/null 2>&1; then
  git remote add origin "git@github.com:$REPO.git"
fi
if [[ -z "$(git log --oneline -1 2>/dev/null)" ]]; then
  git add -A
  git commit -q -m "chore: scaffold $NAME from base-multiplayer-game"
fi
if ! git ls-remote --exit-code --heads origin main >/dev/null 2>&1; then
  echo "==> Pushing main"
  git push -q -u origin main
fi

# ---- 2. labels, milestones, project, views, seeded issues ------------------
mkdir -p .github
python3 scripts/github/setup_project.py "$REPO" "$TITLE" "$SLUG" scripts/github/groundwork-issues.json .github/project.env

# ---- 3. ruleset on the default branch --------------------------------------
if ! gh api "repos/$REPO/rulesets" --jq '.[].name' 2>/dev/null | grep -qx "main: PR required, threads resolved"; then
  echo "==> Applying branch ruleset"
  gh api "repos/$REPO/rulesets" --method POST --input - >/dev/null <<'EOF'
{
  "name": "main: PR required, threads resolved",
  "target": "branch",
  "enforcement": "active",
  "conditions": { "ref_name": { "include": ["~DEFAULT_BRANCH"], "exclude": [] } },
  "rules": [
    { "type": "deletion" },
    { "type": "non_fast_forward" },
    { "type": "pull_request", "parameters": {
        "required_approving_review_count": 0,
        "dismiss_stale_reviews_on_push": true,
        "require_code_owner_review": false,
        "require_last_push_approval": false,
        "required_review_thread_resolution": true,
        "allowed_merge_methods": ["squash", "merge"] } }
  ]
}
EOF
fi

# ---- 4. board sync + commit the generated project.env ----------------------
./scripts/project-sync.sh
if [[ -n "$(git status --porcelain .github/project.env)" ]]; then
  # main is now PR-protected, so land project.env through a PR like everything else.
  branch="chore/project-env"
  git checkout -q -b "$branch" 2>/dev/null || git checkout -q "$branch"
  git add .github/project.env
  git commit -q -m "chore: record GitHub project ids for project-sync.sh"
  git push -q -u origin "$branch"
  gh pr create -R "$REPO" -B main -t "chore: record GitHub project ids" -b "Generated by scripts/github-setup.sh. Used by scripts/project-sync.sh and scripts/issue-status.sh." >/dev/null
  gh pr merge -R "$REPO" --squash --delete-branch --auto >/dev/null 2>&1 || gh pr merge -R "$REPO" --squash --delete-branch >/dev/null
  git checkout -q main && git pull -q
fi

cat <<EOF

GitHub ready: https://github.com/$REPO
  Issues    https://github.com/$REPO/issues        (labels, milestones, epics with sub-issues)
  Board     $(sed -n 's/^PROJECT_NUMBER=//p' .github/project.env | xargs -I{} echo "https://github.com/users/$GH_USER/projects/{}")
  Your inbox (waiting on you)  https://github.com/issues/assigned
Rules: WORKFLOW.md — PR required, reviewers run on every PR, all review threads resolved before merge.
EOF
